### ISSUE TITLE
Visualization using python 

### ISSUE THREAD

**Issue by keirymb** [Fields2Cover/Fields2Cover#120] opened 2024-04-12 02:52 UTC
I tried the Python tutorials on the repository, but none of the visualizations work. When I attempted part 3, the Headland generator, and tried to visualize it, the shape was plotted but the headland didn't appear. Additionally, no errors were generated. When I attempted part 6, Path planning, I encountered the following error. What am I doing wrong?

![image](https://github.com/Fields2Cover/Fields2Cover/assets/113727612/e40da3b4-7248-4e60-9c89-f65081d026c5)

**Comment by Gonzalo-Mier** [comment] 2024-04-12 12:49
Hi @keirymb,

Did you run the tutorials provided by the repo or did you copy-paste the information from the documentation online? They should work fine. Those warnings are not new and you can safely ignore them. I check the code on my machine and in CodeSpace with docker and I couldn't reproduce your issue.

Also, give us more information about your operative system.

**Comment by Gonzalo-Mier** [comment] 2024-05-06 11:28
I'll close it as there is no further progress on this issue. Feel free to open it again if the error still persists.

**Closed by Gonzalo-Mier** 2024-05-06 11:28 UTC
