### ISSUE TITLE
Compilation on Ubuntu 22.04, gcc 11.3

### ISSUE THREAD

**Issue by jfulem** [Fields2Cover/Fields2Cover#47] opened 2023-01-11 18:00 UTC
@Gonzalo-Mier, just to let you know. I compiled F2C on Ubuntu 22.04 with Python 3.10.6. It works great for me.
Then I compiled it on Ubuntu 20.04 with Python 3.10.9 as well - this requires a slight modification of CMake.
```python
find_package(Python3 3.10 EXACT REQUIRED COMPONENTS Interpreter Development)

if(Python_VERSION VERSION_GREATER_EQUAL 3)
  list(APPEND CMAKE_SWIG_FLAGS "-py3;-DPY3")
endif()

if(BUILD_DOC)
  list(APPEND CMAKE_SWIG_FLAGS "-doxygen")
endif()

set(CMAKE_SWIG_FLAGS "")
set_source_files_properties(../${PROJECT_NAME}.i PROPERTIES CPLUSPLUS ON)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../include/ ${Python3_INCLUDE_DIRS} )
file(GLOB_RECURSE Swig_SRC "${CMAKE_CURRENT_SOURCE_DIR}/../../include/fields2cover.h")

# Add swig module
SWIG_ADD_LIBRARY(fields2cover_python LANGUAGE python SOURCES ../${PROJECT_NAME}.i)
swig_link_libraries(fields2cover_python Fields2Cover ${Python3_LIBRARIES} ${PROJ_LIBRARY} ${GDAL_LIBRARIES})
```
But there is one strange thing in both cases.

This works:
```python
n = path.states.size()
points = [path.states[i].point for i in range(n)]
```

This is crashing when iterating through the list of `points` after it's created:

```python
states = list(path.states)
points = [item.point for item in states]
```

**Comment by vinnnyr** [comment] 2023-01-11 18:57
is it segfaulting? can you provide a bit more detail on the nature of the crash? I ask because I think I saw something similar.

**Comment by jfulem** [comment] 2023-01-11 22:16
It's pretty hard because it dies really silently. For example, when I was debugging it just to hover the mouse over the `points` list, the process simply exited.

**Comment by Gonzalo-Mier** [comment] 2023-01-12 13:15
Thanks for noticing it @jfulem. 
I'm working on it. I've also noticed on the Python interface that I cannot concatenate some operations because it crash, so it's needed to do it step by step. 
I'll come later with a solution or more tests (and a headache).

**Comment by jfulem** [comment] 2023-01-13 07:10
@Gonzalo-Mier, perfect. Thank you.

**Comment by Gonzalo-Mier** [comment] 2023-01-13 13:42
@jfulem I haven't been able to reproduce the error. I would like to ask you which GDAL and SWIG version are you using? 
According to [SWIG docs](https://sourceforge.net/p/swig/news/2022/10/swig-410-released/), version 4.1.0 solves some memory leaks on Python. You could try to improve the swig version, and check if this error still happens. Unfortunately, a few python tests fail on that version. I'll continue trying to fix it.

On the other hand, are you able to create a test on a Docker that replicates this issue? On the [add_gdal_version_support branch](https://github.com/Fields2Cover/Fields2Cover/tree/add_gdal_version_support) I've update the Dockerfile to be able to modify the GDAL version at the beginning.

**Comment by jfulem** [comment] 2023-01-13 15:59
I used swing 4.0.2 and GDAL 3.4.3. I can make the test on a Docker, yes.

**Comment by Gonzalo-Mier** [comment] 2023-01-16 12:50
I wasn't able to replicate this issue: https://github.com/Fields2Cover/Fields2Cover/blob/fix_issue_47/tests/python/types/Path_test.py#L211-L212

I also created a docker with the same versions of your system and it works well. @jfulem, could you try to run the python tests of the branch [fix_issue_47](https://github.com/Fields2Cover/Fields2Cover/tree/fix_issue_47) to see if the test covers this issue correctly?

**Comment by Gonzalo-Mier** [comment] 2023-01-16 15:26
I've updated the path on the test and it seems to also work without failure. Now it contains 173554 points. I don't know if we are missing something. Thanks for taking the time.

**Comment by jfulem** [comment] 2023-01-16 17:46
@Gonzalo-Mier, I checked the test. It looks like it's working fine. I will test it in my project using F2C for initial harvesters' path planning. But the test works fine.

**Comment by Gonzalo-Mier** [comment] 2023-01-20 00:14
@jfulem were you able to test it? Should I close this issue?

**Comment by jfulem** [comment] 2023-01-20 07:33
I was able to test it and it is still causing the issues. I'm trying to replicate it in the test. The problem is that I have an object which reads the field and creates the paths and the points. Then accessing X and Y from the created `points` from another python object basically crashes. To avoid the crash I have to do something like this:
```python
states = list(path.states)
self.points = [item.point for item in states]
xp = [p.getX() for p in self.points] # to avoid crash
yp = [p.getY() for p in self.points] # to avoid crash
```
Then I can retrieve the `points` list in another class/object and I can iterate through the points there.

**Comment by Botronics** [comment] 2023-01-20 07:35
Hai sir . i am using ros noetic . i did all the procedures given. but still i am getting error. 
![Screenshot from 2023-01-20 13-04-33](https://user-images.githubusercontent.com/110804545/213641683-8d878a8e-6f5f-4343-8b92-c10ce2dac893.png)

**Comment by Gonzalo-Mier** [comment] 2023-01-20 11:03
Hi @Botronics, 
as your problem comes from a different issue, I would suggest you to open a new issue so we could discuss it without interferences. Please, open a new issue on https://github.com/Fields2Cover/fields2cover_ros and we would try to fix it :)

This message and the previous one will be deleted in a few days.

**Comment by Gonzalo-Mier** [comment] 2023-01-24 10:46
Hi @jfulem, 
Please, try to make a unit test. I'm not able to debug it with this information. Thanks for your time

**Comment by jfulem** [comment] 2023-01-25 10:34
@Gonzalo-Mier , I tried to mimic our structure to reproduce the issue: https://github.com/jfulem/Fields2Cover/tree/fix_issue_47
But it looks like it's working just fine in the tests. So, I think the issue is somewhere else and you can probably close this issue.

**Comment by Gonzalo-Mier** [comment] 2023-01-25 11:37
I'll close it then. Please, feel free to re-open this issue if you find it again.

**Closed by Gonzalo-Mier** 2023-01-25 11:37 UTC
